# https://docs.docker.com/compose/compose-file/05-services/#image
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ARG COMPOSER_VERSION: 2.6.5
        ARG PHP_VERSION: 8.2
        ARG BOX_VERSION: 4.5.1
        ARG BOX_CHECKSUM: c24c400c424a68041d7af146c71943bf1acc0c5abafa45297c503b832b9c6b16
        ARG GIT_EMAIL: "seb@local.fr"
        ARG GIT_USERNAME: "seb"
        ARG ALPINE_VERSION: 3.19
        ARG PHP_CS_FIXER_VERSION: 3.52.1
#    expose:
#      - 8000
    expose:
      # php-fpm
      - 9000
    ports:
      # symfony dev server
      - target: 8000
        published: 32771
    volumes:
      # application
      - type: bind
        source: ./
        target: /app
    user: "0:1000"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    # service name is the hostname
    # @todo : utiliser un fichier de config pour la version de postgres
    image: postgres:16.1
    environment:
      # @todo : changer ces valeurs pour la prod, utiliser un fichier de config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_symfony
    expose:
      - 5432
    # ports : pour debogage - ne pas  utiliser en prod @todo
    ports:
      - target: 5432
        published: 32770
    # mettre en place volumes en prod @todo
    #    volumes:
    #      - type: volume
    #        source: postgres_data
    #        target: /var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:1.21.3
    ports:
      - target: 80
        published: 32772
    volumes:
      # nginx config
      - type: bind
        source: ./configs/nginx_default.conf
        target: /etc/nginx/conf.d/default.conf
      # assets
      - type: bind
        source: ./public
        target: /app/public
    depends_on:
      - php
    restart: unless-stopped

# @todo configurer les reseaux pour limiter au maximum les acces
# networks:
#   my_symfony:
#volumes:
#  postgres_data:
