name: symfonystarter
services:
  nginx:
    depends_on:
      php:
        condition: service_started
    expose:
      - "${NGINX_PORT}"
    image: nginx:1.21.3
    networks:
      nginx: null
    ports:
      - target: 80
        published: "${NGINX_PORT}"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/nginx_default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./public
        target: /app/public
  php:
    depends_on:
      postgres:
        condition: service_started
    image: ghcr.io/sebsept/docker-php-symfony-starter:main
    networks:
      nginx: null
      postgres: null
    restart: unless-stopped
    user: 0:1000
    volumes:
      - type: bind
        source: ./
        target: /app
  postgres:
    environment:
      POSTGRES_DB: my_symfony
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - "${POSTGRES_PORT}"
    image: postgres:16.1
    networks:
      postgres: null
    ports:
      - target: 5432
        published: "${POSTGRES_PORT}"
    restart: unless-stopped
networks:
  nginx:
    name: composer-starter_nginx
  postgres:
    name: composer-starter_postgres
